version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=sqlite:///common.db
    depends_on:
      - db
  db:
    image: "postgres:latest"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: